# Forces new Travis-CI Infrastructure
sudo: false

language: php

matrix:
  fast_finish: true
  include:
    - php: 5.6
    #- php: 7.0
    - php: 7.1
    - php: nightly
# current is 3.15 dev
    - php: hhvm
      sudo: true
      dist: trusty
      group: edge # until the next update
      addons:
        apt:
          packages:
            - mysql-server-5.6
            - mysql-client-core-5.6
            - mysql-client-5.6
      services:
        - mysql
        - postgresql
        - memcache
        - memcached
        - redis-server
      env: HHVMPHP7="no"
    - php: hhvm
      sudo: true
      dist: trusty
      group: edge # until the next update
      addons:
        apt:
          packages:
            - mysql-server-5.6
            - mysql-client-core-5.6
            - mysql-client-5.6
      services:
        - mysql
        - postgresql
        - memcache
        - memcached
        - redis-server
      env: HHVMPHP7="yes"
    - php: hhvm-nightly
      sudo: true
      dist: trusty
      group: edge # until the next update
      addons:
        apt:
          packages:
            - mysql-server-5.6
            - mysql-client-core-5.6
            - mysql-client-5.6
      services:
        - mysql
        - postgresql
        - memcache
        - memcached
        - redis-server
      env: HHVMPHP7="no"
    - php: hhvm-nightly
      sudo: true
      dist: trusty
      group: edge # until the next update
      addons:
        apt:
          packages:
            - mysql-server-5.6
            - mysql-client-core-5.6
            - mysql-client-5.6
      services:
        - mysql
        - postgresql
        - memcache
        - memcached
        - redis-server
      env: HHVMPHP7="yes"
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: nightly

services:
  - memcache
  - memcached
  - redis-server

before_script:
  # Make sure all dev dependencies are installed
  - composer install
  - composer update
  - composer dump-autoload
  - if [[ $TRAVIS_PHP_VERSION != hhv* ]]; then php -r 'ini_set("hhvm.php7.all", 1);'; fi
  - if [[ $HHVMPHP7 == "yes" ]]; then echo hhvm.php7.all=1 >> /etc/hhvm/php.ini; fi

script:
  #- if [[ $TRAVIS_PHP_VERSION != hhv* ]]; then php testAutoloaders.php; fi
  #- if [[ $TRAVIS_PHP_VERSION = hhv* ]]; then hhvm --php testAutoloaders.php; fi
  - if [[ $TRAVIS_PHP_VERSION != hhv* ]]; then php testNullTypes.php; fi
  - if [[ $TRAVIS_PHP_VERSION = hhv* ]]; then hhvm --php testNullTypes.php; fi
  
